# GitHub Pages Overrides (not configurable locally)
safe: true
lsi: false
source: .
baseurl: ''

# GitHub Pages Settings
highlighter: pygments

# Personal Jekyll Config
exclude: [vendor,script]
timezone: America/New_York
paginate: 10
paginate_path: "/page:num/"
sass:
    sass_dir: _sass
